name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - deployment/initial
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - deployment/initial

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v3
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_WONDERFUL_GLACIER_022757E03 }}
          action: "upload"  # Ensure this is set
          app_location: "/"  # App source code path
          api_location: ""    # Api source code path - optional
          output_location: "build"  # Built app content directory - optional

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "close"
